### ISSUE TITLE
centos 7 with 0.4.0 patching as code causing continual reboots

### ISSUE THREAD

**Issue by xandrellas** [puppetlabs/puppetlabs-patching_as_code#15]
Hey folks, 

just started using 0.4.0 release and ended up with some pretty wild behaviors.  
 puppet-agent[28695]: Patching as Code - Pending OS reboot detected, node will reboot at start of patch window today
 puppet-agent[28695]: Patching as Code - Performing Pending OS reboot before patching...
 puppet-agent[28695]: (/Notify[Patching as Code - Performing Pending OS reboot before patching...]/message) defined 'message' as 'Patching as Code - Performing Pending OS reboot before patching...' 
 puppet-agent[28695]: (/Notify[Patching as Code - Performing Pending OS reboot before patching...]) Scheduling refresh of Reboot[Patching as Code - Pending OS reboot]
 puppet-agent[28695]: Scheduling system reboot with message: "Puppet is rebooting the computer" 
 puppet-agent[28695]: (/Reboot[Patching as Code - Pending OS reboot]) Triggered 'refresh' from 1 event
 puppet-agent[28695]: Applied catalog in 11.58 seconds

This ended up in 15-20 reboots before I finally reverted back to 0.3.0 in my control repo, which patched the nodes but did not complete a reboot (necessary) after.  Thoughts?  

mod 'noma4i-windows_updates', '0.3.0'
mod 'puppetlabs-powershell', '3.0.1'
mod 'puppetlabs-pwshlib', '0.7.0'
mod 'puppetlabs-puppet_agent', '4.4.0'
mod 'puppetlabs-reboot', '2.4.0'

I had to librarian-puppet my Puppetfile quite mega to handle all the dependencies - noted that puppetlabs-reboot is at 3.2.0.  That a potential?  There's not much in the patching_as_code documentation about using puppetlabs-reboot and any version dependencies.

Thoughts?

**Comment by kreeuwijk** [comment]
Due to a testing oversight, a logic error sneaked in that caused the exitcode of `needs-restarting` to get parsed incorrectly.
This has now been fixed, along with another tweak on managing the `yum-utils` package.
Please upgrade to version 0.4.3 and it will work correctly.

**Comment by kreeuwijk** [comment]
puppetlabs-reboot was indeed missing from the dependency list, I've added that in as well.
