### ISSUE TITLE
Reboots unreliable - `refreshonly ==>true`

### ISSUE THREAD

**Issue by noahbliss** [puppetlabs/puppetlabs-patching_as_code#25]
I've been working on standing up patching_as_code on the latest community version of puppet (7) and am using version 7.7.0 of the agent. I am using this with the wsus_client module (checking for updates hourly) and the os_patching module. 

My target client systems are all windows. 

Both wsus_client and os_patching appear to behave as expected (although os_patching only refreshes twice a day as part of the scheduled task) however reboots invoked by patching_as_code have proven unreliable. I was able to obtain the expected behavior by commenting out `refreshonly ==> true` on line 327 of `/etc/puppetlabs/code/environments/production/modules/patching_as_code/manifests/init.pp` but I am not certain _why_ this is. When running `puppet agent --debug` as NT AUTHORITY\SYSTEM I noticed fail lines related to this setting. 

This issue is just to create visibility, hopefully get an understanding of _why_ this issue happens and this fix works, and to provide any other confused people with a workaround. 

Thanks!

**Comment by kreeuwijk** [comment]
Hi @noahbliss, the reboot behavior you're referring to is for the `reboot: ifneeded` setting, which is the default setting. This works through the `Exec` resource that you mentioned, and gets triggered to execute by any patch getting installed. Please don't remove `refreshonly => true` as that will make the `Exec` resource always trigger, even if no patches are installed.

When a patch is installed, the `Exec` resource gets notified, which will first run the `$reboot_logic_onlyif` command to see if the system reports that it needs a reboot. On Windows, that is this [script](https://github.com/puppetlabs/puppetlabs-patching_as_code/blob/master/lib/patching_as_code/pending_reboot.ps1). If the script returns the system not needed a reboot, the reboot is skipped. I'm assuming that this is what you find "unreliable" behavior.

If you would like to have the node always reboot after patching, regardless of whether the system reports it requires a reboot or not, simply change the reboot setting to `reboot: always`.

**Comment by noahbliss** [comment]
You're right in that the Exec resource always triggers now, but because of the `reboot_logic_onlyif` the system still appears to skip reboots if one wasn't pending, and having the Exec portion of the code being invoked seems to make the clients more responsive to actually patching during the patching window. On the handful of clients I've been testing with, it also seemed that without this adjustment some have been completely skipping patch installation during the maintenance window.

**Comment by kreeuwijk** [comment]
Hi Noah, can you share a puppet run report from such an example? The modification of the `Exec` resource shouldn't have any effect on what patches get installed.
Also, is there a time zone difference between the PE server and the managed nodes? Because if this time difference is big enough to cause a date difference between the two during the patch run (e.g. if the patch window is configured close to midnight), then this can cause patch runs to not apply patches on the expected day.

**Comment by kreeuwijk** [comment]
@noahbliss please try version 0.7.0 of the module, which revamps the reboot logic.

**Comment by noahbliss** [comment]
So far it all appears to be working as expected, I'll close this and loop back if anything else comes up after more testing. But otherwise should be able to consider this resolved. Thanks!
