### ISSUE TITLE
Cannot reboot during "Active hours" window on Windows

### ISSUE THREAD

**Issue by noahbliss** [puppetlabs/puppetlabs-patching_as_code#26]
Latest puppet open source server, agent is 7.7.0. 

If the patching_as_code maintenance window is within the "Active hours" configured in Windows Update settings, reboots will not occur.

**Comment by noahbliss** [comment]
Default windows "Active hours" window is from 8AM to 5PM local server time for anyone reading this. Schedule your patch window outside of those hours as a workaround.

**Comment by kreeuwijk** [comment]
Hi @noahbliss, the reboot capabilities in `patching_as_code` do not honor the Active Hours in Windows, so this cannot be the reason for reboots not occurring. I'm assuming the actual reason for your issue is in #25, so I'll close this one for now.
