### ISSUE TITLE
potential race condition? issue RE: patching_configuration.json

### ISSUE THREAD

**Issue by xandrellas** [puppetlabs/puppetlabs-patching_as_code#36]
updated to latest forge module release as well as the updated albatross os_patching module.

receiving error :

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /etc/puppetlabs/code/environments/<sanitized>/modules/patching_as_code/functions/is_patchday.pp, line: 50, column: 24) on node <sanitized>
Warning: Not using cache on failed catalog

This is properly updated/addressed when I throw in another host that can resolve or has its own configuration.json file.

Unsure exactly what the behavior is, but if that file does not exist or is empty, havoc ensues and the catalog won't compile.  

Host OS's :  Centos 7, ubuntu 16/18/20, RedHat 7.

Thoughts/seen this?

**Comment by xandrellas** [comment]
Additionally - if I remove patching_configuration.json and re-run puppet agent I end up in the same original issue as before.  Uncertain what I am missing, if it is the issue at hand, flag/key-wise to ensure this goes cleanly.

**Comment by kreeuwijk** [comment]
@xandrellas oh I see, it goes wrong trying to access a sub-element from `patching_as_code_config` if the fact doesn't exist yet.
I'll add in some logic to properly handle this.

**Comment by kreeuwijk** [comment]
@xandrellas fixed in version `0.7.7`, now on the Forge
