### ISSUE TITLE
potential chicken/egg issue regarding new os_patching fact storage?

### ISSUE THREAD

**Issue by xandrellas** [puppetlabs/puppetlabs-patching_as_code#48]
Heya - I updated our Puppetfile to use 1.0.4 patching_as_code from 0.7.9

the creation of `/opt/puppetlabs/os_patching` as a directory appears to be impeding a run from completing.

Puppet agent version: 6.25.1
Please advise

Error: Could not set 'file' on ensure: No such file or directory - A directory component in /opt/puppetlabs/os_patching/patching_as_code_last_run20220301-24293-1oviczh.lock does not exist or is a dangling symbolic link (file: /etc/puppetlabs/code/environments/${ENV}/modules/patching_as_code/manifests/init.pp, line: 372)
Error: Could not set 'file' on ensure: No such file or directory - A directory component in /opt/puppetlabs/os_patching/patching_as_code_last_run20220301-24293-1oviczh.lock does not exist or is a dangling symbolic link (file: /etc/puppetlabs/code/environments/${ENV}/modules/patching_as_code/manifests/init.pp, line: 372)
Wrapped exception:
No such file or directory - A directory component in /opt/puppetlabs/os_patching/patching_as_code_last_run20220301-24293-1oviczh.lock does not exist or is a dangling symbolic link
Error: /Stage[main]/Patching_as_code/File[Patching as Code - Save Patch Run Info]/ensure: change from 'absent' to 'file' failed: Could not set 'file' on ensure: No such file or directory - A directory component in /opt/puppetlabs/os_patching/patching_as_code_last_run20220301-24293-1oviczh.lock does not exist or is a dangling symbolic link (file: /etc/puppetlabs/code/environments/prod/modules/patching_as_code/manifests/init.pp, line: 372)

**Comment by xandrellas** [comment]
centos7 node

**Comment by kreeuwijk** [comment]
@xandrellas ah I see, `os_patching` actually uses `/var/cache/os_patching` as the cache dir, not `/opt/puppetlabs/os_patching`. I'll update that and publish v1.0.5 with a fix.

**Comment by xandrellas** [comment]
Hi Kevin - the behaviors seem to be inconsistent on my end, going host to host checking, so am trying to find a proverbial ghost in the machine but nothing really standing out just yet
