### ISSUE TITLE
Quartal patching instead of monthly

### ISSUE THREAD

**Issue by anissmajlovic** [puppetlabs/puppetlabs-patching_as_code#52]
## Use Case
A clear and concise description of what the problem you're trying to solve is. Ex. I'm always frustrated when [...]
---
We are quite bit organization and for us monthly patching is very hard to achieve. I am wondering is it possible to set patching every 3 months. 

## Describe the Solution You Would Like
---
For example in patch schedule group we have only 5 weeks across single month, but could we have 12 weeks across 3 months.

## Describe Alternatives You've Considered
---
I know that this is maybe complicated to have as feature, could I download PaC and try to find in code and customize but I am not sure where is this set count_of_week. I would appreciate for any hint.

**Comment by kreeuwijk** [comment]
At this point, a cycle longer than 1 month is not supported by PaC itself. However, you can use the [change_window](https://forge.puppet.com/modules/puppetlabs/change_window) module to create more custom change windows than monthly, and use that together with PaC to solve the problem.

**Comment by anissmajlovic** [comment]
Thanks
