### ISSUE TITLE
RHEL Packages with "nn:" in the version are not being detected by `os_patching`

### ISSUE THREAD

**Issue by cosmocaan** [puppetlabs/puppetlabs-patching_as_code#60]
## Describe the Bug
When we are patching using puppet_as_code, we found a few packages were not being updated and narrowed the cause to the package version having a ":" in the text IE the  "32:" in the output of `yum check-update`:
  bind-export-libs.x86_64                                                                32:9.11.4-26.P2.el7_9.9

The packages can be updated manually with `yum -y update` which confirms it is patching_as_code not caching the "nn:" versioned packaged.

## Expected Behavior
I expect all packages to be updated in my puppet run and after the server reboots, `yum check-update` should show zero packages need to be updated.

## Steps to Reproduce
1. Run puppet agent -t and see packages updating
2. After the reboot, run `yum check-update`
3. Review the list of packages still available for update (notice the "nn:" in the version)
4. Check facts for os_patching and there are no packages listed because the "nn:" packages are skipped:
  package_update_count => 0,
  package_updates => [

  ],

## Environment
 - RHEL 6
 - RHEL 7

**Comment by kreeuwijk** [comment]
Interesting. The detection of packages needing updates isn't done by `patching_as_code` however, instead that data is read from the output of the `os_patching` module (or `pe_patch` on Puppet Enterprise). I will inform the team that owns that of this problem so they can fix it.

**Comment by cosmocaan** [comment]
Thank you Kevin! I see that now in the script.  Looks like regex needs tuning?  I see issue #212<https://github.com/albatrossflavour/puppet_os_patching/issues/212> opened for this same issue.

Michael Thomasson
Sr. Administrator, IT Operations, Midrange 4
817-948-8986
 [AAAAABJRU5ErkJggg==]
[Logo  Description automatically generated]

From: Kevin Reeuwijk ***@***.***>
Date: Wednesday, July 6, 2022 at 4:59 AM
To: puppetlabs/puppetlabs-patching_as_code ***@***.***>
Cc: Thomasson, Mike ***@***.***>, Author ***@***.***>
Subject: Re: [puppetlabs/puppetlabs-patching_as_code] RHEL Packages with "nn:" in the version are not being updated with patching_as_code (Issue #60)

Interesting. The detection of packages needing updates isn't done by patching_as_code however, instead that data is read from the output of the os_patching module (or pe_patch on Puppet Enterprise). I will inform the team that owns that of this problem so they can fix it.

**Comment by kreeuwijk** [comment]
Probably, yes. You can hit up `@greeno` on the Puppet Community slack to put the question to the author directly.
