### ISSUE TITLE
PDK Update, style guidelines, documentation

### ISSUE THREAD

**Issue by brajjan** [puppetlabs/puppetlabs-patching_as_code#67]
## Use Case
PDK version is currently 2.0.0, lots of style guidelines fixes needs to be applied

## Describe the Solution You Would Like
Update PDK to latest version and fix errors such as trailing commas and other syntax
Update documentation of parameters
Add data types where missing
Optional parameters does not default to undef

**Comment by kreeuwijk** [comment]
Fixed in v1.1.7 of the module, now available on the Forge
