### ISSUE TITLE
Always reboot triggers pre reboot scripts even if no patching is done

### ISSUE THREAD

**Issue by Perkka2** [puppetlabs/puppetlabs-patching_as_code#68]
## Describe the Bug
The always reboot flag makes the pre reboot script trigger every time puppet runs.

## Expected Behavior
The pre reboot script should only run when actual patching has taken place.

## Steps to Reproduce
Create a manifest including a patch group that patches whenever a new patch comes and uses reboot always.
Add a pre_reboot_command
run puppet, the pre_reboot_command will trigger each and every run

## Environment
 - Version puppetserver version: 7.9.0
 - Version puppetlabs-patching_as_code (v1.1.4)
 - Platform Debian 11

**Comment by kreeuwijk** [comment]
Confirmed, looking into a solution.

**Comment by kreeuwijk** [comment]
@Perkka2 This is now fixed in release 1.1.6
