### ISSUE TITLE
Incorrect Code Manager/r10k declaration

### ISSUE THREAD

**Issue by morgan-lillie** [puppetlabs/puppetlabs-patching_as_code#7]
## Describe the Bug
The module won't load when Puppetfile declaration is inserted as presented

## Expected Behavior
The line can be inserted into a Puppetfile and the module will be present

## Steps to Reproduce
Insert line into Puppetfile and observe that class is not available in PE console

## Additional Context
Single quotes need adding, fixes issue

**Comment by kreeuwijk** [comment]
This is a generic Forge issue, I'll let them know. Closing this issue as that setting isn't controlled by any module
